name: test 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    uses: leonardo-ornelas/check-PR-base-branch-action@main
    with:
      spec: >
        {
        "develop": ["feature/.*", "hotfix/.*","release/.*"],
        "master": ["dev"]"
        }
