name: test 
on:
  pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: get branch
        run: echo 'is dev'


        